Use deterministic time for generated sdist files
python-poetry/poetry-core pull request #142
Opened 2021-03-22 00:56 UTC by abn

When generating setup.py and PKG-INFO files, ensure that generated
files use a deterministic timestamp to enhance reproducibility of
source distributions.

Resolves: python-poetry#1102

2021-03-22 09:49 UTC, Natureshadow commented
I propose that this code should use `SOURCE_DATE_EPOCH` from environment if set.

cf. https://reproducible-builds.org/docs/source-date-epoch/

2021-03-22 09:57 UTC, Natureshadow requested changes
As suggested earlier, I would propose to use `SOURCE_DATE_EPOCH`.

Defaulting to `0` if it is not set might be ok, I am not sure of that. I somehow tend to leaving the current timestamp as default.

2021-03-22 09:57 UTC, Natureshadow commented on poetry/core/masonry/builders/sdist.py
> +                tar_info = self.clean_tarinfo(tar_info)
```suggestion
                if "SOURCE_DATE_EPOCH" in os.environ:
                    tar_info.mtime = int(os.environ.get("SOURCE_DATE_EPOCH"))
                    tar_info = self.clean_tarinfo(tar_info)
                else:
                    tar_info.mtime = time.time()
```

2021-03-22 09:57 UTC, Natureshadow commented on poetry/core/masonry/builders/sdist.py
> +            tar_info = self.clean_tarinfo(tar_info)
```suggestion
            if "SOURCE_DATE_EPOCH" in os.environ:
                tar_info.mtime = int(os.environ.get("SOURCE_DATE_EPOCH"))
                tar_info = self.clean_tarinfo(tar_info)
            else:
                tar_info.mtime = time.time()
```

2021-03-22 09:57 UTC, Natureshadow commented on tests/masonry/builders/test_sdist.py
> +import hashlib
```suggestion
import hashlib
import os
```

2021-03-22 09:57 UTC, Natureshadow commented on tests/masonry/builders/test_sdist.py
> +    hashes = set()
```suggestion
    hashes = set()
    os.environ["SOURCE_DATE_EPOCH"] = "0"
```

2021-03-22 10:06 UTC, Natureshadow commented
Oh, quoting from https://reproducible-builds.org/specs/source-date-epoch/ , it seems that honouring this variable is a **MUST`` to comply with the reproducible builds standard. I was not aware of this. As such, I make my proposal a bit harder ;).

It also talks about "timestamp clamping", which says that all timestamps that do not use the value from this variable must be earlier, so `0` looks good. It does, however, look wrong to me to use such a pseudo-random magic value. I would therefore stick with `time.time()` if the source epoch is not set.

2021-03-22 16:31 UTC, Natureshadow commented
> Oh, quoting from https://reproducible-builds.org/specs/source-date-epoch/ , it seems that honouring this variable is a **MUST** to comply with the reproducible builds standard. I was not aware of this. As such, I make my proposal a bit harder ;).

Had a chat with the people form reproducible-builds.org.

It seems there were a few misunderstnadings on my side:

* `SOURCE_DATE_EPOCH` is mainly for binary builds, to align it with the source timestamp
* `0` is perfectly fine for reproducibility
* Using a timestamp that somehow reflects the last time the source was modified would be good. One idea is looking at git's `HEAD` if available, another would be to copy the mtime of `pyproject.toml`.

So if the maintainers want to keep it simple, just sticking with 0 seems fine.

2021-04-16 13:33 UTC, stephsamson approved these changes

2021-04-17 13:03 UTC, Natureshadow commented
@stephsamson It seems you reviewed this PR. Did you take my comments into account?

2021-04-17 19:37 UTC, stephsamson commented
@Natureshadow for the purposes of this PR, I think that keeping `tar_info.mtime` to `0` is fine as you mentioned [here yourself](https://github.com/python-poetry/poetry-core/pull/142#issuecomment-804209538) or did I misunderstand? Also, `SOURCE_DATE_EPOCH` as you said is for binary builds so I find that that is out of scope for `sdist` and subsequently this PR and python-poetry#1102.

2021-04-17 22:09 UTC, Natureshadow commented
@stephsamson Yes, I did say that using `0` is fine as well. I just wanted to know your opinion, as you left my change proposals open.

2021-04-19 12:03 UTC, stephsamson commented
@Natureshadow I think that your suggestion, specifically for checking `mtime` of pyproject.toml to use as a timestamp for binary distributions, is a good candidate for a separate issue/refactoring.

2021-04-19 12:03 UTC, merged