fix(packages/dependency): add space after filename for file dependencies with markers
python-poetry/poetry-core pull request #153
Opened 2021-04-01 21:01 UTC by ossareh

Resolves: python-poetry#3872

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

local vendored files need a space after the file name and before the ";" which demarks the start of
markers

2021-04-01 21:07 UTC, ossareh commented
Looking into those windows errors...

2021-04-01 22:22 UTC, ossareh commented
Update: this solves the case of the missing space prior to the ";", but immediately runs up against the fact that a relative file is not a valid URL:

```
...snip...
  File "/home/ossareh/dev/src/github.com/erisyon/vega/.tox/py39/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3033, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/home/ossareh/dev/src/github.com/erisyon/vega/.tox/py39/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "/home/ossareh/dev/src/github.com/erisyon/vega/.tox/py39/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid URL: blob/pyvcam-2.1.0-cp39-cp39-linux_x86_64.whl
```

It's possible that my "fix" is actually fixing the wrong thing; if I was including this as an absolute path with a `file://` scheme the `is_url()` portion of [my change](https://github.com/python-poetry/poetry-core/pull/153/files#diff-4ee16b9cad93048318361c44a6fa750eb1a7d4c891f6f99302cfa9e61b102cdbR265) may actually just do the right thing.

In my case I can't provide an absolute path due to varied setup on hosts that'll receive this code.

I'm going to think about this some more, if you decide the close this PR without merging I understand :) - if you want changes made, I'm happy to make them.

2021-04-02 13:14 UTC, ossareh commented
> It's possible that my "fix" is actually fixing the wrong thing; if I was including this as an absolute path with a file:// scheme the is_url() portion of my change may actually just do the right thing.

after more research I see this is incorrect.

This change makes the output of this stage of the process 508 compliant, where as prior to this it was not. So in that regard this is indeed fixing **a** problem.

The fact that pip doesn't have a solution for understanding relative paths is a well discussed situation: https://github.com/pypa/pip/issues/6658

2021-04-25 19:14 UTC, finswimmer requested changes
Thanks a lot. Looks good to me :+1: 

Just a small suggestion to improve the test.

2021-04-25 19:14 UTC, finswimmer commented on tests/packages/test_file_dependency.py
> +def test_to_pep_508_with_marker(mocker):
I think we can use a parameterize test here, to test absolute and relative path.

2021-04-25 20:00 UTC, ossareh commented
@finswimmer thanks for the feedback 👍

I went ahead and restructured that unit test into two. I considered parameterizing the test and I could see two main options:

 1. a loop which calls the underlying test with an absolute path and a relative path
 2. calling a new `_test_to_508_with_marker` with the paths and expectation which then calls `_test_file_dependency_pep_508`
 3. splitting the unit test into two for each case

I felt the 3rd option strikes the best balance with clarity, it's a step necessary for the 2nd option, and I'm happy to add that additional layer if you think the deduplication is desirable.

2021-04-26 18:55 UTC, finswimmer approved these changes

2021-04-26 19:01 UTC, merged