chore: upgrade codebase to 3.6+
python-poetry/poetry-core pull request #179
Opened 2021-05-18 22:29 UTC by branchvincent

Relates-to: python-poetry/poetry#3860

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

In the same spirit as python-poetry/poetry#3988, this:
* Applies `pyupgrade --py36-plus` to the codebase
* Adds the above to `.pre-commit-config.yaml`

2021-06-11 14:03 UTC, kamyar commented
@branchvincent any specific reason to reopen same change when there is already #3988 ?

2021-06-11 14:19 UTC, branchvincent commented
> @branchvincent any specific reason to reopen same change when there is already #3988 ?

hey @kamyar! your pr is for [poetry](https://github.com/python-poetry/poetry) while this is for [poetry-core](https://github.com/python-poetry/poetry-core)

2021-06-11 14:59 UTC, kamyar commented
Sorry missed that 🤦 😞 
Thank you for pointing it out

2021-07-20 15:44 UTC, Leonardofreua requested changes

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/packages/dependency.py
>                  requirement += " ({})".format(",".join(constraints))
```suggestion
                requirement += f" ({','.join(constraints)})"
```

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/packages/dependency.py
>              requirement += " ({})".format(str(self.constraint).replace(" ", ""))
```suggestion
            requirement += f' ({str(self.constraint).replace(" ", "")})'
```

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/packages/dependency.py
>                  requirement += "; {}".format(" and ".join(markers))
```suggestion
                requirement += f"; {' and '.join(markers)}"
```

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/packages/directory_dependency.py
>              requirement += "[{}]".format(",".join(self.extras))
```suggestion
            requirement += f"[{','.join(self.extras)}]"
```

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/packages/file_dependency.py
>              requirement += "[{}]".format(",".join(self.extras))
```suggestion
            requirement += f"[{','.join(self.extras)}]"
```

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/packages/package.py
>          return "{} {}".format(
It missing to apply the f-string in the last return of the method `full_pretty_version()`.

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/packages/url_dependency.py
>              requirement += "[{}]".format(",".join(self.extras))
```suggestion
            requirement += f"[{','.join(self.extras)}]"
```

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/packages/vcs_dependency.py
>              requirement += "[{}]".format(",".join(self.extras))
```suggestion
            requirement += f"[{','.join(self.extras)}]"
```

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/packages/vcs_dependency.py
>              requirement += " @ {}+ssh://{}@{}".format(
It missing to apply the f-string on line 113.

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/version/pep440/version.py
>              version_string += "+{}".format(".".join(map(str, self.local)))
```suggestion
            version_string += f"+{'.'.join(map(str, self.local))}"
```

2021-07-20 15:44 UTC, Leonardofreua commented on poetry/core/version/requirements.py
> +            parts.append("[{}]".format(",".join(sorted(self.extras))))
```suggestion
            parts.append(f"[{','.join(sorted(self.extras))}]")
```

2021-11-15 22:52 UTC, branchvincent commented
closing in favor of #230

2021-11-15 22:52 UTC, closed without merging