Add support for multiple README files (reworked)
python-poetry/poetry-core pull request #248
Opened 2021-11-16 22:56 UTC by wagnerluis1982

This code reuses the `"readme"` entry in a way to allow the user to declare in the old way or the new way.

With the changes, the two following declarations are valid:

**Single file**
```toml
readme = "README.rst"
```

**Multiple files**
```toml
readme = [
    "README.rst",
    "HISTORY.rst"
]
```

If the user declares files in different formats, the strict validation will issue.

Resolves: python-poetry/poetry#873

- [x] Added **tests** for changed code.
- [x] Updated **documentation** for changed code (python-poetry/poetry#4743).

2021-11-20 19:04 UTC, neersighted requested changes
I'm still not the biggest fan of adding another helper, but we can always move it later during a cleanup of that module.

LGTM after feedback is addressed.

2021-11-20 23:40 UTC, wagnerluis1982 commented
> I'm still not the biggest fan of adding another helper, but we can always move it later during a cleanup of that module.
> 
> LGTM after feedback is addressed.

@neersighted I have to say that I deeply consider about this decision. But the lack of a new helper would mean to store the content type into Package, which doesn't fit IMHO. So I decided to have the helper.

2021-11-21 00:00 UTC, wagnerluis1982 commented on src/poetry/core/factory.py
> +                readme_types = [readme_content_type(r) for r in config["readme"]]
Yeah, i took this decision prematurely, motivated by the fact the `set` gives non-predictable order (which is important for me in the unit test). I am solving this by adding `sorted(readme_types)` in the error message value.

2021-11-21 01:22 UTC, neersighted approved these changes

2021-11-21 01:22 UTC, merged