chore: use fstrings
python-poetry/poetry-core pull request #250
Opened 2021-11-17 03:53 UTC by branchvincent

Towards #4776

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2021-11-18 15:38 UTC, danieleades requested changes
there's quite a few places where the f-strings are *harder* to read than the original syntax. This occurs when the 'structure' of the original message is obscured by the long, inline code.

I commented on the first few, but there's a lot more places here where i think this holds.

In those cases, I would suggest improving clarity by adding intermediate calculations of the message components, and then using the local variables.

the point of this lint is to make things easier to grok, so we need to be careful about cargo-culting in the lint, and missing the point of why we're using it in the first place

2021-11-18 15:38 UTC, danieleades commented on poetry/core/json/__init__.py
> +            message = f"[{'.'.join(str(x) for x in error.absolute_path)}] {message}"
i think this is less clear than the original. consider splitting into two lines
```suggestion
            path = '.'.join(str(x) for x in error.absolute_path)
            message = f"[{path}] {message}"
```

2021-11-18 15:38 UTC, danieleades commented on poetry/core/masonry/builders/sdist.py
> +                f"from {self._package.build_script.split('.')[0]} import *",
as above- this is harder to read than the original

2021-11-18 15:38 UTC, danieleades commented on poetry/core/packages/constraints/constraint.py
> +        return f"{self._operator if self._operator != '==' else ''}{self._version}"
as above

2021-11-18 15:38 UTC, danieleades commented on poetry/core/packages/dependency_group.py
> +        return f"{self.__class__.__name__}({self._name}, optional={self._optional})"
as above

2021-11-19 02:13 UTC, branchvincent commented
thanks @danieleades, hopefully this is more readable

2021-11-19 06:30 UTC, danieleades approved these changes
Looks good to me!

2021-11-19 14:39 UTC, neersighted requested changes
LGTM after one tiny correctness fix! Awesome work!

2021-11-19 14:39 UTC, neersighted commented on src/poetry/core/packages/utils/link.py
> +        return f"<Link {self}>"
```suggestion
        return f"<Link {self!s}>"
```

To keep this code consistent (`%s` implies the same `__str__` but not `__format__` call).

2021-11-20 02:01 UTC, neersighted approved these changes

2021-11-20 02:01 UTC, merged