Fix multiple packages build
python-poetry/poetry-core pull request #292
Opened 2022-02-12 00:51 UTC by lucasiscovici-Loreal

Resolves: multiple packages build

When there are multiple packages with the "from" keyword, the `poetry build` command, doesn't install the packages as expected.
Ex: 
```
packages = [
    { include = "XXX", from = "path/to/dir1" },
    { include = "YYY", from = "path/to/dir2" },
    { include = "ZZZ", from = "path/to/dir3" },
    { include = "A" }
]
```
In fact, when poetry build, its find all the files and directories inside the path specified by the keyword 'from' (['find_files_to_add' function](https://github.com/python-poetry/poetry-core/blob/4e5207e4d41c0c4f1844b1389eef79276af47a49/src/poetry/core/masonry/builders/builder.py#L157) from poetry/core/masonry/builders/builder.py#L157) .
Next, if it's a directory, it find all files and add them with the 'BuildIncludeFile' class using the current path (self._path).
[BuildIncludeFile with self._path](https://github.com/python-poetry/poetry-core/blob/4e5207e4d41c0c4f1844b1389eef79276af47a49/src/poetry/core/masonry/builders/builder.py#L176-L180)
poetry/core/masonry/builders/builder.py#L176-L180
 ```
  include_file = BuildIncludeFile(
      path=current_file,
      project_root=self._path,
      source_root=self._path,
  )
```
If it's a file, it add it with the 'BuildIncludeFile'  BUT using the 'specified **from** keyword' (include.base) if it is defined.
[BuildIncludeFile with include.base](https://github.com/python-poetry/poetry-core/blob/4e5207e4d41c0c4f1844b1389eef79276af47a49/src/poetry/core/masonry/builders/builder.py#L188-L199)
poetry/core/masonry/builders/builder.py#L188-L199
```
  if (
      isinstance(include, PackageInclude)
      and include.source
      and self.format == "wheel"
  ):
      source_root = include.base
  else:
      source_root = self._path

  include_file = BuildIncludeFile(
      path=file, project_root=self._path, source_root=source_root
  )
```

This Pr is intented to use the 'include.base' when it's the directory (if from is defined).
So only move up to the line #L172
```
  if (
      isinstance(include, PackageInclude)
      and include.source
      and self.format == "wheel"
  ):
      source_root = include.base
  else:
      source_root = self._path
```
And use ```source_root=source_root``` for the 'BuildIncludeFile' class in the directory part (#L179).
 

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2022-02-14 09:51 UTC, lucasiscovici-Loreal commented
@python-poetry/triage

2022-02-28 10:00 UTC, lucasiscovici-Loreal commented
@abn @kurtmckee @tomzx

2022-02-28 10:17 UTC, finswimmer commented
Hey @lucasiscovici-Loreal,

could you please add test(s) that cover your changes?

Thanks a lot for your contribution :+1:

fin swimmer

2022-02-28 15:20 UTC, kurtmckee commented
@lucasiscovici-Loreal, thanks for the mention. I'm not yet clear what I need to be aware of, or what help I can offer. How can I help here?

2022-03-01 22:35 UTC, lucasiscovici-Loreal commented
> @lucasiscovici-Loreal, thanks for the mention. I'm not yet clear what I need to be aware of, or what help I can offer. How can I help here?

Hello @kurtmckee, my bad, I wanted to talk to the poetry maintainers

2022-03-08 23:20 UTC, lucasiscovici commented
Hello @finswimmer
https://github.com/python-poetry/poetry-core/blob/1314ad42658fbca47d32d1ed725f1bec86c9a815/src/poetry/core/masonry/builders/builder.py#L188-L199

Do you know why there are a check for a wheel format (line 191 - self.format == "wheel" )  ? 
Why not for the sdist format ?

2022-03-08 23:53 UTC, lucasiscovici-Loreal commented
> Hey @lucasiscovici-Loreal,
> 
> could you please add test(s) that cover your changes?
> 
> Thanks a lot for your contribution 👍
> 
> fin swimmer

Hello, @finswimmer, it's ok

2022-03-09 00:05 UTC, abn requested changes

2022-03-09 00:05 UTC, abn commented on tests/masonry/builders/test_complete.py
> +    module_path = fixtures_dir / "split_source"
Looks like the fixture was not added?

2022-03-09 00:08 UTC, abn commented on tests/masonry/builders/test_complete.py
> +    module_path = fixtures_dir / "split_source"
Nevermind. Just noticed it is an existing one.

2022-03-09 00:08 UTC, abn approved these changes

2022-03-09 00:11 UTC, merged

2022-04-28 08:30 UTC, lucasiscovici-Loreal commented
@abn  @finswimmer  hello when the new release please ?