Fix Version.next_devrelease() when starting with a prerelease.
python-poetry/poetry-core pull request #295
Opened 2022-02-14 19:14 UTC by sherbang

Version('1.2.3-pre.0').next_devrelease() raises an exception, and Version('1.2.3-dev.0').next_devrelease() doesn't change the version.  It seems that this code was probably copied from next_prerelease(), but not completely updated from pre to dev?

The version/expected list is based on the behavior of next_prerelease().  I'm not sure if this is the most "correct" logic here?  I removed passing pre to the created version because turning "1.2.3-alpha.0" into "1.2.3-alpha.0-dev.0" didn't seem right, but I'm not sure that turning it into "1.2.3-dev.0" is right either.

- [X ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

2022-03-05 01:02 UTC, abn commented
Technically `1.2.3-alpha.0.dev.0` is a pre-release to the pre-release `1.2.3-alpha.0`. But in this case I suspect the right behaviour is to bump to `1.2.3-alpha.1.dev.0`. This means the last set component gets bumped prior to initialising `dev` release. So `1.2.3 -> 1.2.4-dev0`, `1.2.3-post1 -> 1.2.3-post2.dev0` etc.

2022-03-08 14:09 UTC, sherbang commented
> Technically `1.2.3-alpha.0.dev.0` is a pre-release to the pre-release `1.2.3-alpha.0`. But in this case I suspect the right behaviour is to bump to `1.2.3-alpha.1.dev.0`. This means the last set component gets bumped prior to initialising `dev` release. So `1.2.3 -> 1.2.4-dev0`, `1.2.3-post1 -> 1.2.3-post2.dev0` etc.

That's an option for sure.  In this case I was just trying to make the logic not obviously broken.

Right now, `Version('1.2.3-dev.0').next_devrelease()` doesn't do anything and that's obviously wrong, with this patch it will return `Version('1.2.3-dev.1')` which is correct.

I consider the `Version('1.2.3-pre.0').next_devrelease() ` behavior to be more of a corner-case.  The alpha+dev type versioning will likely be controversial no matter which approach is chosen and some people will use it and others will just implement their own versioning logic (which I ended up doing anyway because I didn't like how the release tags kept getting expanded).

2022-03-09 01:11 UTC, abn requested changes

2022-03-09 01:11 UTC, abn commented on src/poetry/core/version/pep440/version.py
> +        return self.__class__(epoch=self.epoch, release=self.release, dev=dev)
```suggestion
        return self.__class__(epoch=self.epoch, release=self.release, pre=self.pre, post=self.post, dev=dev)
```

Let's retain the pre and post release for now. Handling of next pre-release, post-release when dev is set can be addressed in another PR.

2022-03-09 01:11 UTC, abn commented on tests/semver/test_version.py
> +        ("1.2.3-dev.0", "1.2.3-dev.1"),
```suggestion
        ("1.2.3", "1.2.3-dev.0"),
        ("1.2.3-alpha.0", "1.2.3-alpha.0-dev.0"),
        ("1.2.3-dev.0", "1.2.3-dev.1"),
```

2022-03-09 01:30 UTC, abn approved these changes
Approving this now as it solves the dev release bumps. Pre/post release dev release handling to improved in follow-up PRs.

2022-03-09 01:52 UTC, abn commented
Merged via https://github.com/python-poetry/poetry-core/commit/4781c82b2a0326fd344fbb28c721b58f8551b81a

2022-03-09 01:52 UTC, closed without merging