release: bump to version 1.1.0-rc.1
python-poetry/poetry-core pull request #443
Opened 2022-08-16 15:14 UTC by finswimmer

### Changed
- Removed unused code ([#419](https://github.com/python-poetry/poetry-core/pull/419)).
- Replaced Poetry's helper method canonicalize_name() by packaging.utils.canonicalize_name() ([#418](https://github.com/python-poetry/poetry-core/pull/418)).

### Fixed
- Fixed an issue with Python constraints from markers ([#436](https://github.com/python-poetry/poetry-core/pull/436)).
- Fixed an issue where equal markers had not the same hash ([#417](https://github.com/python-poetry/poetry-core/pull/417)).
- Fixed allows_any for local versions ([#433)](https://github.com/python-poetry/poetry-core/pull/433)).
- Fixed an issue with marker, that results in incorrectly resolved extra dependencies ([#415](https://github.com/python-poetry/poetry-core/pull/415)).

2022-08-16 17:52 UTC, radoering requested changes
My pedantic self is struggling with the reversed chronological order of the issues but think I can accept it. 😉

Just some minor improvements.

2022-08-16 17:52 UTC, radoering commented on CHANGELOG.md
> +- Fixed an issue with marker, that results in incorrectly resolved extra dependencies ([#415](https://github.com/python-poetry/poetry-core/pull/415)).
```suggestion
- Fixed an issue with markers, that results in incorrectly resolved extra dependencies ([#415](https://github.com/python-poetry/poetry-core/pull/415)).
```

2022-08-16 17:52 UTC, radoering commented on CHANGELOG.md
> +- Replaced Poetry's helper method canonicalize_name() by packaging.utils.canonicalize_name() ([#418](https://github.com/python-poetry/poetry-core/pull/418)).
```suggestion
- Replaced Poetry's helper method `canonicalize_name()` by `packaging.utils.canonicalize_name()` ([#418](https://github.com/python-poetry/poetry-core/pull/418)).
```

2022-08-16 17:52 UTC, radoering commented on CHANGELOG.md
> +- Fixed allows_any for local versions ([#433)](https://github.com/python-poetry/poetry-core/pull/433)).
```suggestion
- Fixed `allows_any()` for local versions ([#433)](https://github.com/python-poetry/poetry-core/pull/433)).
```

2022-08-16 19:32 UTC, radoering approved these changes

2022-08-16 19:55 UTC, mkniewallner submitted a review, later dismissed

2022-08-17 04:36 UTC, radoering requested changes
Added another fix. Proposal for changelog entry:

Fixed special cases of `next_major()`, `next_minor()`, etc. and deprecated ambiguous usage ([#434](https://github.com/python-poetry/poetry-core/pull/434)).

2022-08-17 09:34 UTC, mkniewallner approved these changes

2022-08-17 09:53 UTC, merged