Fixes unstable next breaking version when major is 0
python-poetry/poetry-core pull request #475
Opened 2022-09-16 17:57 UTC by mazinesy

Resolves: https://github.com/python-poetry/poetry/issues/6519

- [ ] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code.

### Extra info
It would be great to have to have a `poetry build` step that checks the `requires_dist` output against poetry to make sure the package is actually usable.

2022-09-16 18:17 UTC, mazinesy commented on src/poetry/core/semver/version.py
> +                print(self.is_unstable())
😢

2022-09-16 21:00 UTC, dimbleby reviewed
This seems a reasonable interpretation of `next_breaking()` to me, as well as apparently being what poetry 1.1 used to do.  On the other hand the unfixed interpretation _also_ seems reasonable, so I'd welcome maintainer opinion...

Per https://github.com/python-poetry/poetry/issues/6519#issuecomment-1249794969, it's not clear that this is really the problem that you wanted to solve anyway.

2022-09-16 21:42 UTC, dimbleby commented
on further investigating PEP440 I no longer think that the unfixed interpretation is reasonable 

> "The exclusive ordered comparison <V MUST NOT allow a pre-release of the specified version unless the specified version is itself a pre-release"

So eg `>=0.0.2a1,<0.0.2` is actually empty (since the second part explicitly excludes the pre-releases).

That doesn't seem like a useful meaning of `^0.0.2a1` at all

So this looks good to me

2022-09-17 08:54 UTC, radoering requested changes
There are still some cases that might not be correct:

`^0.1` becomes `>=0.1,<0.2`

but

`^0.1-alpha.1` becomes `>=0.1-alpha.1,<0.1.1`

That's probably not expected, is it?

Can you add a dedicated unit test for `next_breaking` in `tests/semver/test_version.py` similar to the tests in `tests/pep440/test_version.py` for the `next_...` methods of `PEP440Version`, please?

2022-09-17 11:04 UTC, dimbleby commented
good spot.

There's more than one way to skin a cat, but I'll re-suggest https://github.com/python-poetry/poetry/issues/6519#issuecomment-1247339637

> suggest that next_breaking() wants to start by going `stable = self.stable` and then consider `stable` everywhere it currently considers self.

> And add a testcase in [here](https://github.com/python-poetry/poetry-core/blob/main/tests/semver/test_version.py) - next_breaking() has no coverage at the moment so the more the merrier, cf the tests for next_major() and next_minor() and suchlike.

2022-09-20 14:03 UTC, mazinesy commented
> There are still some cases that might not be correct:

@radoering 
I thought `0.2-alpha1` was not a valid version, but looking through PEP440, it is. I will add the test cases for this and also will add test cases for the `Version` class. I thought it was weird we had no tests for that class and everything was in `helper`.

There's also a general issue where `Version.next_breaking()` is keeping the precision. There's a [test](https://github.com/python-poetry/poetry-core/blob/main/tests/semver/test_helpers.py#L383) for this. But `Version.stable` breaks the versioning.

`Version` is in the `semver` package which would imply it represents a `semver` version. But, `Version.next_breaking` allows for non semver versions even if it is in the `SemverVersion` class. Here are my thoughts:

1. `Version.stable` breaks the version precision where no other `SemverVersion` method does
2. `Version.next_breaking()` currently does not break the precision, but should break. Since `^` is not a valid PEP440 constraint, when someone asks for `^1.1`, it makes sense to basically say, evaluate `^1.1.0`

2022-09-20 17:16 UTC, mazinesy commented
My last comment feels a bit too much opinionated so I kept the precision in `next_breaking()`, but maybe, `next_breaking()` should live in `PEP440Version` as it keeps precision

2022-09-20 18:31 UTC, dimbleby commented
oh also I now notice that you've changed the implementation of stable() so that it sometimes returns a postrelease. (I was blind to this before on account of it moving between classes).  

Again this seems like a change that is somewhere between not-needed-right-now and I-dont-even-know-whether-its-right.

2022-09-20 18:46 UTC, mazinesy commented
Here are some example of what `stable` used to do:
```
version => stable
0.2 => 0.2
0.2-a1 => 0.2.1 (adds precision)
1 => 1
1-alpha.1 => 1.0.1 (adds precision)
```
Very weird behaviour and it was used in `next_breaking()`.

The reason why `next_breaking` never does a patch bump for 0 majors comes from a test that described the expected behaviour [here](https://github.com/python-poetry/poetry-core/blob/main/tests/packages/test_dependency.py#L164). Plus, this is the current behaviour on main. But I see that this example did not have a `0` as minor, that's where my problem is. I'll fix that.

So the expected behavior's for next_breaking are:

```
0 => 1
0.1 => 0.2
0.0.1 => 0.0.2 (minor is also 0)
0.1.2 => 0.2.0 (minor is not 0)
```

Adding `-alpha.x` does not change that behavior.

2022-09-20 19:28 UTC, mazinesy commented
> We're talking past each other. I've no problem with `stable()` being fixed to preserve precision. I am (i) asking why it moved to a different class and (ii) suggesting a simpler implementation.

(i)
The main reason being that `Version` represents a `SemVer` version which must be in `X.Y.Z`. Currently, doing `Version.parse("0.1")` yields `Version<0.1>` which is an invalid semver version as `semver` always has a precision of 3. My logic is, everything that deals with `preserving` versions should live in `PEP440Version` version and not the `semverVersion`. From this, the current implementation of `next_breaking()` should also live in `PEP440Version`

(ii) I just implemented it

2022-09-20 19:47 UTC, dimbleby commented
poetry-core's `Version` does not always have a precision of three.  So moving this code out of the `Version` class for that reason is unnecessary.

I propose that the entire diff in `src` should look like this:
```patch
diff --git a/src/poetry/core/semver/version.py b/src/poetry/core/semver/version.py
index 2fe6fe8..4746121 100644
--- a/src/poetry/core/semver/version.py
+++ b/src/poetry/core/semver/version.py
@@ -32,21 +32,17 @@ class Version(PEP440Version, VersionRangeConstraint):
         if self.is_stable():
             return self

-        return self.next_patch()
+        post = self.post if self.pre is None else None
+        return Version(release=self.release, post=post, epoch=self.epoch)

     def next_breaking(self) -> Version:
-        if self.major == 0:
-            if self.minor is not None and self.minor != 0:
-                return self.next_minor()
+        if self.major > 0 or self.minor is None:
+            return self.stable.next_major()

-            if self.precision == 1:
-                return self.next_major()
-            elif self.precision == 2:
-                return self.next_minor()
+        if self.minor > 0 or self.precision == 2:
+            return self.stable.next_minor()

-            return self.next_patch()
-
-        return self.stable.next_major()
+        return self.stable.next_patch()
```

your tests for `stable()` will then want moving (because they go with the `Version` and not the `PEP440Version`.  And I think that will expose some differences eg `1.2.3.4dev0.stable()` will be `1.2.3.4` - which seems correct.

2022-09-20 19:59 UTC, mazinesy commented
> your tests for `stable()` will then want moving (because they go with the `Version` and not the `PEP440Version`. And I think that will expose some differences eg `1.2.3.4dev0.stable()` will be `1.2.3.4` - which seems correct.

Alright, let me move things around. Btw, SonarCloud is freaking out because `1.2.3.4` looks like an IP address.

I'll restate my concern about the following even if this PR won't deal with it.
```python
@dataclasses.dataclass(frozen=True)
class Version(PEP440Version, VersionRangeConstraint):
    """
    A parsed semantic version number.
    """
    ...

# This should not work as `0.1` is not a valid semantic version
Version.parse('0.1').text == "0.1"

# Either, raises an error
Version.parse("0.1")

# Or
Version.parse("0.1").text == "0.1.0"
```

2022-09-20 20:08 UTC, dimbleby approved these changes
looks good to me but (i) I'm more or less reviewing my own code at this point and (ii) my review doesn't count for anything anyway

2022-09-20 20:37 UTC, mazinesy commented
@radoering would you be so kind to rereview this PR and there seems to be an issue with SonarCloud which thinks the version `1.2.3.4` is an IP address

2022-09-22 16:47 UTC, radoering commented
> I'll restate my concern about the following even if this PR won't deal with it.

The class has some semver related methods (like `next_breaking`) but apart from that it's just a specific `VersionConstraint` representing a single version and not necessarily a semantic version number. Maybe, we should just remove the docstring because it's more confusing than helpful. Actually, `semver` is not even a suitable name for the package anymore, but that's something for another PR.

2022-09-23 09:56 UTC, radoering approved these changes

2022-09-23 10:08 UTC, merged