Cleanup pyproject
python-poetry/poetry-core pull request #589
Opened 2023-05-15 23:18 UTC by Secrus

Resolves: python-poetry/poetry#7929

- Moved dev dependencies to groups
- Removed `pyrsistent` from dev dependencies (it's vendored anyway)
- Removed `exclude` directive (.pyi files are required for tests, .pyc are ignored by git)
- Removed `generate-setup-file = false` as it is now a default setting
- Removed redundant include directive from `black` config

2023-05-16 03:58 UTC, radoering requested changes

2023-05-16 03:58 UTC, radoering commented on pyproject.toml
>  pytest-mock = ">=3.5"
```suggestion
pytest-mock = ">=3.10"
```

https://github.com/python-poetry/poetry/issues/7929#issuecomment-1547859865

2023-05-16 07:57 UTC, branchvincent commented on pyproject.toml
>  line-length = 88
can remove this default as well

2023-05-18 22:14 UTC, Secrus commented on pyproject.toml
>  pytest-mock = ">=3.5"
Done

2023-05-18 22:14 UTC, Secrus commented on pyproject.toml
>  line-length = 88
Done

2023-05-19 02:04 UTC, branchvincent approved these changes

2023-05-19 07:20 UTC, radoering approved these changes

2023-05-19 08:54 UTC, merged