Explicity Define Build Platlib Dir From Build Env
python-poetry/poetry-core pull request #726
Opened 2024-04-30 18:52 UTC by grabpot

When poetry-core is not run in the build environment, the build platlib directory, in particular the cache_tag string, is now derived from the build environment via a subprocess call, similar to _get_sys_tags(). Previously build platlib was always derived from the poetry-core environment, resulting in a build error if the Python version differed between the poetry-core and build environments.

Resolves: python-poetry [#9344](https://github.com/python-poetry/poetry/issues/9344)

No new tests added. Changes tested by existing build_with_build_py_only test.
No change to documentation required.

2024-05-01 11:06 UTC, radoering requested changes
some minor suggestions

2024-05-01 11:06 UTC, radoering commented on src/poetry/core/masonry/builders/wheel.py
> +        return self._path / "build" / ("lib." + plat_specifier)
```suggestion
        return self._path / "build" / f"lib.{plat_specifier}"
```

2024-05-01 11:06 UTC, radoering commented on src/poetry/core/masonry/builders/wheel.py
> +                    "Failed to get platform-cache_tag for python interpreter"
```suggestion
                    "Failed to get build_platlib_dir for python interpreter"
```

2024-05-01 13:10 UTC, grabpot commented on src/poetry/core/masonry/builders/wheel.py
> +                )
Fixed in ed8d73a

2024-05-05 14:28 UTC, radoering approved these changes

2024-05-05 14:29 UTC, merged