Add SOURCE_DATE_EPOCH support when building packages
python-poetry/poetry-core pull request #766
Opened 2024-10-02 21:51 UTC by Secrus

Resolves: python-poetry/poetry#3531

- [x] Added **tests** for changed code.
- [ ] Updated **documentation** for changed code. (Not sure where the docs about that should go, since poetry-core doesn't have separate docs)

2024-10-02 22:00 UTC, trag1c requested changes
<sub>i accidentally submitted a review in the wrong tab</sub>

2024-10-03 09:02 UTC, radoering requested changes

2024-10-06 12:54 UTC, Secrus commented on src/poetry/core/masonry/builders/sdist.py
> +    def add_file_to_tar(
Honestly, I didn't understand the reason for `clean_tarinfo` to be a `classmethod`, so I don't think I will be changing those unless you see any of those decisions being wrong.

2024-10-06 13:08 UTC, Secrus commented on tests/masonry/builders/test_sdist.py
> -            assert tarinfo.mtime > 0
Overzealous deletion from my side, restored

2024-10-06 13:41 UTC, Secrus commented on src/poetry/core/masonry/builders/sdist.py
> +                logger.info(
Redid the rules, let me know what you think.

2024-10-06 13:41 UTC, Secrus commented on src/poetry/core/masonry/builders/wheel.py
> +            if _env_date[0] < 1980:
Done

2024-10-07 15:50 UTC, radoering commented on tests/masonry/builders/test_sdist.py
> +    from _pytest.monkeypatch import MonkeyPatch
cf #772 😉

LGTM apart from that and a conflict to resolve.

2024-10-07 16:06 UTC, radoering approved these changes

2024-10-07 16:06 UTC, merged